import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Hydration from "@/provider/hydration";
import Store from "@/provider/store";
import { SearchProvider } from "../Contexts/SearchContext"; // Assuming SearchProvider is correctly imported
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SearchProvider>
        <Store>
          <Hydration>
            {children}
          </Hydration>
        </Store>
        </SearchProvider>
        <Toaster />
      
      </body>
    </html>
  );
}
