import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Hydration from "@/provider/hydration";
import Tutor from "@/provider/tutor";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body >
        <Tutor>
          <Hydration>
              {children}
          </Hydration>
        </Tutor>
      </body>
    </html>
  );
}